/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NguoiDungRouteImport } from './routes/nguoi-dung'
import { Route as MocRouteImport } from './routes/moc'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CauHinhRouteImport } from './routes/cau-hinh'
import { Route as IndexRouteImport } from './routes/index'

const NguoiDungRoute = NguoiDungRouteImport.update({
  id: '/nguoi-dung',
  path: '/nguoi-dung',
  getParentRoute: () => rootRouteImport,
} as any)
const MocRoute = MocRouteImport.update({
  id: '/moc',
  path: '/moc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CauHinhRoute = CauHinhRouteImport.update({
  id: '/cau-hinh',
  path: '/cau-hinh',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cau-hinh': typeof CauHinhRoute
  '/login': typeof LoginRoute
  '/moc': typeof MocRoute
  '/nguoi-dung': typeof NguoiDungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cau-hinh': typeof CauHinhRoute
  '/login': typeof LoginRoute
  '/moc': typeof MocRoute
  '/nguoi-dung': typeof NguoiDungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cau-hinh': typeof CauHinhRoute
  '/login': typeof LoginRoute
  '/moc': typeof MocRoute
  '/nguoi-dung': typeof NguoiDungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cau-hinh' | '/login' | '/moc' | '/nguoi-dung'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cau-hinh' | '/login' | '/moc' | '/nguoi-dung'
  id: '__root__' | '/' | '/cau-hinh' | '/login' | '/moc' | '/nguoi-dung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CauHinhRoute: typeof CauHinhRoute
  LoginRoute: typeof LoginRoute
  MocRoute: typeof MocRoute
  NguoiDungRoute: typeof NguoiDungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nguoi-dung': {
      id: '/nguoi-dung'
      path: '/nguoi-dung'
      fullPath: '/nguoi-dung'
      preLoaderRoute: typeof NguoiDungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moc': {
      id: '/moc'
      path: '/moc'
      fullPath: '/moc'
      preLoaderRoute: typeof MocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cau-hinh': {
      id: '/cau-hinh'
      path: '/cau-hinh'
      fullPath: '/cau-hinh'
      preLoaderRoute: typeof CauHinhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CauHinhRoute: CauHinhRoute,
  LoginRoute: LoginRoute,
  MocRoute: MocRoute,
  NguoiDungRoute: NguoiDungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
